apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- model-registry-configmap.yaml
- model-registry-deployment.yaml
- model-registry-service.yaml
- model-registry-sa.yaml
images:
- name: quay.io/opendatahub/model-registry
  newName: quay.io/opendatahub/model-registry
  newTag: v0.2.16
